version: '3.8'
services:
  fastapi-service:
    build: ./fastapi-service
    ports:
      - "8002:8000"
    networks:
      - ism-net
  kong-db:
    image: postgres:13
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    ports:
      - "5433:5432"
    networks:
      - ism-net
  kong:
    image: kong:3.4
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_PASSWORD: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    depends_on:
      - kong-db
    ports:
      - "8000:8000" # Proxy
      - "8001:8001" # Admin API
    networks:
      - ism-net
networks:
  ism-net:
    driver: bridge 